Uml
Codrux2200/Rtype pull request #2
Opened 2023-09-19 15:50 UTC by Codrux2200

## Description
Implementation of hpp's UML

## Lien tache Jira
UML

## Changement
ECS/*.hpp
ECS/system/*.hpp

2023-09-19 18:06 UTC, raphaelMrci requested changes
Rename files, be careful with namespaces, be CamelCase compliant, be careful when overriding virtual methods by specifying you are overriding them, write clean code and it should be good

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/AudioSystem.hpp
> +            void init(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/EventSystem.hpp
> +            void init(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/EventSystem.hpp
> +            void Update(SceneManager &SceneManager, int deltaTime);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/EventSystem.hpp
> +            void Destroy(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GameSystem.hpp
> +            void init(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GameSystem.hpp
> +            void Update(SceneManager &SceneManager, int deltaTime);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GameSystem.hpp
> +            void Destroy(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GraphicSystem.hpp
> +            void init(SceneManager &SceneManager);
it is an override

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GraphicSystem.hpp
> +            void Update(SceneManager &SceneManager, int deltaTime);
Same thing s as other, I'm tired lol

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/GraphicSystem.hpp
> +            void Destroy(SceneManager &SceneManager);
Same thing s as other, I'm tired lol

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/iSystem.hpp
> +        GRAPHIQUE = 1,
It will be better in english ???

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/system/iSystem.hpp
> +        GRAPHIQUE = 1,
(GRAPHIC)

2023-09-19 18:06 UTC, raphaelMrci commented on ecs/scene.hpp
Rename the file

2023-09-19 18:29 UTC, mangasteak commented on CMakeLists.txt
> +target_include_directories(MySFMLProject PRIVATE ${SFML_INCLUDE_DIRS} ${ASIO_INCLUDE_DIRS} ${CMAKE_CURRENT_SOURCE_DIR}/ecs)
il me semble que tu n'as pas a inclure les hpp nn ?

2023-09-19 18:36 UTC, mangasteak commented on ecs/components/healthComponent.hpp
> +class healthComponent : public ECS::Acomponent {
is it realy necessary for class name ?

2023-09-19 18:51 UTC, mangasteak requested changes
Raphael did review the most things, nothing to serious , just be carefull with the names of class and files

2023-09-19 18:51 UTC, mangasteak commented on ecs/system/EventSystem.hpp
> +#include "iSystem.hpp"
Upercase at the beggining for FileName

2023-09-19 19:27 UTC, raphaelMrci commented on ecs/components/healthComponent.hpp
> +class healthComponent : public ECS::Acomponent {
> is it realy necessary for class name ?

Especially for class names

2023-09-19 19:28 UTC, raphaelMrci commented on ecs/components/healthComponent.hpp
> +class healthComponent : public ECS::Acomponent {
I prefer the class to be outside the namespace, than that ! It is the basics of CamelCase

2023-09-20 13:05 UTC, mangasteak requested changes

2023-09-20 13:05 UTC, mangasteak commented on ecs/components/ShootComponent.hpp
> +            ShootComponent(int uid, int shootSpeed, int shootDamage);
should first letter of constructor / destructor be in Maj ?

2023-09-20 13:05 UTC, mangasteak commented on ecs/system/ParticleSystem.hpp
> +            void Update(SceneManager &SceneManager, int deltaTime) override;
why does the Caps of the first letter of functions are irregular ?

2023-09-20 13:19 UTC, christophechr commented on ecs/components/ShootComponent.hpp
> +            ShootComponent(int uid, int shootSpeed, int shootDamage);
Constructor and destructor mostly in caps following the class case style.

2023-09-20 13:43 UTC, mangasteak requested changes

2023-09-20 13:43 UTC, mangasteak commented on ecs/Core.hpp
> +#include "./system/ISystem.hpp"
relative path have to be resolved with CMAKE

2023-09-20 13:43 UTC, mangasteak commented on ecs/system/AudioSystem.hpp
> +** RtypeExperimentation
remove the experimentation from the header :)

2023-09-20 15:28 UTC, raphaelMrci requested changes

2023-09-20 15:28 UTC, raphaelMrci commented on ecs/IComponent.hpp
> +            int _uid;
No declaration of things in interfaces

2023-09-20 15:28 UTC, raphaelMrci commented on ecs/Scene.hpp
> +            void loadEntity(std::string entityName);
underscores

2023-09-20 15:28 UTC, raphaelMrci commented on ecs/Scene.hpp
> +            void loadEntity(std::string entityName);
apply on other variables

2023-09-20 15:28 UTC, raphaelMrci commented on ecs/system/AudioSystem.hpp
> +            void init(SceneManager &SceneManager) override;
Lowercase for method params PLSSSS

2023-09-20 15:28 UTC, raphaelMrci commented on ecs/system/AudioSystem.hpp
> +            void init(SceneManager &SceneManager) override;
Valable for rest of the PR

2023-09-20 15:43 UTC, raphaelMrci approved these changes
Why do you use `init` and `destroy` methods instead of using Constructors and Destroyers ? @Codrux2200

2023-09-20 15:50 UTC, raphaelMrci approved these changes

2023-09-25 08:50 UTC, mangasteak approved these changes

2023-09-25 08:50 UTC, merged